import axios from 'axios';

/**
 * Building Registry (건축물대장) API Client
 *
 * Uses the 국토교통부 건축물대장정보 서비스 API to fetch building information
 * including building type (주용도코드명) which tells us if it's 아파트 vs 연립/다세대
 *
 * API Documentation: https://www.data.go.kr/data/15134735/openapi.do
 */

export type BuildingType = 'apartment' | 'multifamily' | 'officetel' | 'unknown';

export interface BuildingInfo {
  buildingType: BuildingType;
  buildingTypeName: string; // Original Korean name (아파트, 연립주택, 다세대주택, etc.)
  mainPurpsCd: string; // Building purpose code
  totalFloorArea?: number; // 연면적
  groundFloorCount?: number; // 지상 층수
  undergroundFloorCount?: number; // 지하 층수
  useAprDay?: string; // 사용승인일
  newOldRegstrGbCd?: string; // 신규/기존 구분
}

export interface BuildingRegistryResponse {
  success: boolean;
  data?: BuildingInfo;
  error?: string;
}

/**
 * MOLIT API uses different dong codes than Building Registry API.
 * This mapping converts MOLIT codes (used in address-data.ts) to Building Registry codes.
 * Format: { [sigunguCd]: { [molitDongCode]: registryDongCode } }
 *
 * Auto-generated by scripts/map-all-dong-codes.mjs
 */
const MOLIT_TO_REGISTRY_DONG_CODE: Record<string, Record<string, string>> = {
  // 종로구 (11110)
  '11110': {
    '10100': '14600', '10200': '12900', '10300': '13400', '10400': '14800', '10500': '12700',
    '10600': '15500', '10700': '13500', '10800': '12800', '10900': '17600', '11000': '18000',
    '11100': '18200', '11200': '10300', '11300': '13100', '11400': '13700', '11500': '11800',
    '11600': '11400', '11700': '10900', '11800': '11000', '11900': '11700', '12000': '11600',
    '12100': '15300', '12200': '16800', '12300': '12300', '12400': '12400', '12500': '12500',
    '12600': '12600', '12700': '15100', '12800': '18700', '12900': '15200', '13000': '18400',
    '13100': '14400', '13200': '11500', '13300': '14000', '13400': '12300', '13500': '11900',
    '13600': '14200', '13700': '17800', '13800': '14500', '13900': '12400', '14000': '17500',
    '14100': '10200', '14200': '12000', '14300': '12100', '14400': '18600', '14500': '14100',
    '14600': '16600', '14700': '16000', '14800': '15800', '14900': '11100', '15000': '13000',
    '15100': '13200', '15200': '15900', '15300': '14900', '15400': '16500', '15500': '13300',
    '15600': '13600', '15700': '15700', '15800': '15400', '15900': '14700', '16000': '10700',
    '16100': '12600', '16200': '13800', '16300': '15600', '16400': '16100', '16500': '16300',
    '16600': '16400', '16700': '12500', '16800': '10500', '16900': '17400', '17000': '10100',
    '17100': '12200', '17200': '11200', '17300': '16700', '17400': '10600', '17500': '10800',
    '17600': '13900', '17700': '12700', '17800': '18300', '17900': '11300', '18000': '18100',
    '18100': '16900', '18200': '18500', '18300': '17900', '18400': '14300', '18500': '10400',
    '18600': '16200', '18700': '15000',
  },
  // 중구 (11140)
  '11140': {
    '10100': '14500', '10200': '14600', '10300': '10600', '10400': '11500', '10500': '11600',
    '10600': '11700', '10700': '11800', '10800': '12800', '10900': '12900', '11000': '13000',
    '11100': '11200', '11200': '14000', '11300': '10200', '11400': '17300', '11500': '17400',
    '11600': '12600', '11700': '12700', '11800': '10100', '11900': '16400', '12000': '13600',
    '12100': '15300', '12200': '11900', '12300': '12000', '12400': '11300', '12500': '15700',
    '12600': '10700', '12700': '16600', '12800': '11100', '12900': '11000', '13000': '10800',
    '13100': '16800', '13200': '16200', '13300': '14700', '13400': '13400', '13500': '13500',
    '13600': '14200', '13700': '15400', '13800': '10400', '13900': '10500', '14000': '15500',
    '14100': '15000', '14200': '15100', '14300': '14800', '14400': '14900', '14500': '16900',
    '14600': '17200', '14700': '16000', '14800': '13400', '14900': '15600', '15000': '10900',
    '15100': '14300', '15200': '14400', '15300': '13100', '15400': '16100', '15500': '13600',
    '15600': '15200', '15700': '14100', '15800': '17100', '15900': '12400', '16000': '12500',
    '16100': '15800', '16200': '13200', '16300': '13300', '16400': '17000', '16500': '10300',
    '16600': '11400', '16700': '13700', '16800': '13800', '16900': '13900', '17000': '16500',
    '17100': '12100', '17200': '12200', '17300': '12300', '17400': '16300',
  },
  // 용산구 (11170)
  '11170': {
    '10100': '10400', '10200': '10500', '10300': '12000', '10400': '13200', '10500': '10700',
    '10600': '12200', '10700': '13600', '10800': '11500', '10900': '10800', '11000': '13300',
    '11100': '12300', '11200': '11400', '11300': '12100', '11400': '10600', '11500': '10200',
    '11600': '12600', '11700': '10300', '11800': '12700', '11900': '13500', '12000': '11200',
    '12100': '11300', '12200': '11700', '12300': '11800', '12400': '12900', '12500': '13000',
    '12600': '13400', '12700': '11600', '12800': '10900', '12900': '11000', '13000': '11100',
    '13100': '12400', '13200': '12500', '13300': '12800', '13400': '13100', '13500': '11900',
    '13600': '10100',
  },
  // 성동구 (11200)
  '11200': {
    '10100': '10900', '10200': '11000', '10300': '11100', '10400': '11200', '10500': '10400',
    '10600': '10500', '10700': '10600', '10800': '10100', '10900': '11400', '11000': '11500',
    '11100': '11800', '11200': '11300', '11300': '12200', '11400': '10800', '11500': '10200',
    '11600': '10700', '11700': '10300',
  },
  // 광진구 (11215)
  '11215': {
    '10100': '10500', '10200': '10300', '10300': '10200', '10400': '10400', '10500': '10900',
    '10600': '10100', '10700': '10700',
  },
  // 동대문구 (11230)
  '11230': {
    '10100': '10100', '10200': '10500', '10300': '10200', '10400': '10600', '10500': '10400',
    '10600': '11000', '10700': '10300', '10800': '10700', '10900': '10800', '11000': '10900',
  },
  // 중랑구 (11260)
  '11260': {
    '10100': '10500', '10200': '10100', '10300': '10400', '10400': '10200', '10500': '10600',
    '10600': '10300',
  },
  // 성북구 (11290)
  '11290': {
    '10100': '13400', '10200': '10300', '10300': '11600', '10400': '11700', '10500': '11800',
    '10600': '11900', '10700': '12000', '10800': '10400', '10900': '10500', '11000': '10600',
    '11100': '10700', '11200': '10800', '11300': '10900', '11400': '11000', '11500': '13000',
    '11600': '13100', '11700': '13200', '11800': '12600', '11900': '12700', '12000': '12800',
    '12100': '12900', '12200': '11100', '12300': '11200', '12400': '11300', '12500': '11400',
    '12600': '11500', '12700': '13700', '12800': '13900', '12900': '10100', '13000': '10200',
    '13100': '12100', '13200': '12200', '13300': '12300', '13400': '12400', '13500': '12500',
    '13600': '13800', '13700': '13300', '13800': '13500', '13900': '13600',
  },
  // 강북구 (11305)
  '11305': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10400',
  },
  // 도봉구 (11320)
  '11320': {
    '10100': '10800', '10200': '10600', '10300': '10500', '10400': '10700',
  },
  // 노원구 (11350)
  '11350': {
    '10100': '10300', '10200': '10500', '10300': '10200', '10400': '10600', '10500': '10400',
  },
  // 은평구 (11380)
  '11380': {
    '10100': '10400', '10200': '10500', '10300': '10200', '10400': '10600', '10500': '10300',
    '10600': '10100', '10700': '10900', '10800': '10800', '10900': '10700', '11000': '11000',
    '11100': '11400',
  },
  // 서대문구 (11410)
  '11410': {
    '10100': '10500', '10200': '11300', '10300': '11200', '10400': '10400', '10500': '11500',
    '10600': '11000', '10700': '12000', '10800': '11900', '10900': '11400', '11000': '11700',
    '11100': '10800', '11200': '10700', '11300': '11600', '11400': '10600', '11500': '10100',
    '11600': '10200', '11700': '10300', '11800': '10900', '11900': '11800', '12000': '11100',
  },
  // 마포구 (11440)
  '11440': {
    '10100': '10200', '10200': '11000', '10300': '11800', '10400': '10800', '10500': '10400',
    '10600': '12100', '10700': '10700', '10800': '12300', '10900': '11500', '11000': '12700',
    '11100': '12000', '11200': '12500', '11300': '10300', '11400': '11100', '11500': '11700',
    '11600': '10100', '11700': '12400', '11800': '10900', '11900': '10500', '12000': '11600',
    '12100': '11400', '12200': '10600', '12300': '12200', '12400': '11200',
  },
  // 양천구 (11470)
  '11470': {
    '10100': '10200', '10200': '10300', '10300': '10100',
  },
  // 강서구 (11500)
  '11500': {
    '10100': '10300', '10200': '10200', '10300': '10100', '10400': '10700', '10500': '11200',
    '10600': '10500', '10700': '10400', '10800': '11300', '10900': '10800', '11000': '11000',
  },
  // 구로구 (11530)
  '11530': {
    '10100': '10200', '10200': '10300', '10300': '10900', '10400': '10600', '10500': '10700',
    '10600': '10100', '10700': '10800', '10800': '11000', '10900': '11100', '11000': '11200',
  },
  // 금천구 (11545)
  '11545': {
    '10100': '10100', '10200': '10200', '10300': '10300',
  },
  // 영등포구 (11560)
  '11560': {
    '10100': '11900', '10200': '13200', '10300': '12500', '10400': '11000', '10500': '11100',
    '10600': '13300', '10700': '11800', '10800': '10100',
  },
  // 동작구 (11590)
  '11590': {
    '10100': '10100', '10200': '10800', '10300': '10600', '10400': '10400', '10500': '10700',
    '10600': '10200', '10700': '10900', '10800': '10500',
  },
  // 관악구 (11620)
  '11620': {
    '10100': '10100', '10200': '10300', '10300': '10200',
  },
  // 서초구 (11650)
  '11650': {
    '10100': '10800', '10200': '10200', '10300': '11000', '10400': '10300', '10500': '10400',
    '10600': '10100', '10700': '10600', '10800': '10700', '10900': '10900',
  },
  // 강남구 (11680)
  '11680': {
    '10200': '10700', '10300': '10300', '10400': '11000', '10500': '10600', '10600': '10500',
    '10650': '11300', '10700': '11800', '10800': '10800', '10900': '10100', '11000': '11500',
    '11100': '11400', '11200': '10400',
  },
  // 송파구 (11710)
  '11710': {
    '10100': '10100', '10200': '11300', '10300': '11400', '10400': '10800', '10500': '11100',
    '10600': '10200', '10700': '10600', '10800': '10500', '10900': '10400', '11000': '11200',
    '11100': '10900', '11200': '10300',
  },
  // 강동구 (11740)
  '11740': {
    '10100': '10900', '10200': '10800', '10300': '10200', '10400': '10600', '10500': '10100',
    '10600': '10500', '10700': '10300', '10800': '11000',
  },

  // ============ GYEONGGI DISTRICTS ============
  // 수원시 장안구 (41111)
  '41111': {
    '10100': '12900', '10200': '13000', '10300': '13100', '10400': '13200', '10500': '13300',
    '10600': '13400', '10700': '13500', '10800': '13600', '10900': '13700',
  },
  // 수원시 권선구 (41113)
  '41113': {
    '10100': '13700', '10200': '12600', '10300': '12700', '10400': '13100', '10500': '13200',
    '10600': '13400', '10700': '13500', '10800': '13300', '10900': '14000',
  },
  // 수원시 팔달구 (41115)
  '41115': {
    '10100': '12000', '10200': '12100', '10300': '12200', '10400': '14100', '10500': '13400',
    '10600': '13500', '10700': '13600', '10800': '14000', '10900': '13300', '11000': '13900',
    '11100': '13700', '11200': '13800',
  },
  // 수원시 영통구 (41117)
  '41117': {
    '10100': '10500', '10200': '10700', '10300': '10200', '10400': '10300', '10500': '10400',
    '10600': '10600', '10700': '10700',
  },
  // 성남시 수정구 (41131)
  '41131': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10400', '10500': '10500',
    '10600': '10600', '10700': '10700', '10800': '10800', '10900': '11600', '11000': '11500',
    '11100': '11200',
  },
  // 성남시 중원구 (41133)
  '41133': {
    '10100': '10100', '10200': '13200', '10300': '10300', '10400': '10400', '10500': '10500',
    '10600': '10900', '10700': '10700', '10800': '10600', '10900': '10800',
  },
  // 성남시 분당구 (41135)
  '41135': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10500', '10500': '10600',
    '10600': '10700', '10700': '10800', '10800': '10900', '10900': '11000', '11000': '11100',
    '11100': '11200', '11200': '11300', '11300': '11400', '11400': '11500', '11500': '11600',
  },
  // 의정부시 (41150)
  '41150': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10400', '10500': '10600',
    '10600': '11000', '10700': '10900', '10800': '11100',
  },
  // 안양시 만안구 (41171)
  '41171': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10400',
  },
  // 안양시 동안구 (41173)
  '41173': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10400', '10500': '10500',
    '10600': '10600',
  },
  // 부천시 (41190)
  '41190': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10400', '10500': '10500',
    '10600': '10600', '10700': '10700', '10800': '10800', '10900': '10900', '11000': '11000',
    '11100': '11100', '11200': '11200', '11300': '11300', '11400': '11400',
  },
  // 광명시 (41210)
  '41210': {
    '10100': '10200', '10200': '10100', '10300': '10300', '10400': '10400', '10500': '10600',
    '10600': '10700', '10700': '10500',
  },
  // 평택시 (41220)
  '41220': {
    '10100': '11800', '10200': '12300', '10300': '11000', '10400': '11700', '10500': '12400',
    '10600': '11900', '10700': '12000', '10800': '10900', '10900': '10900',
  },
  // 안산시 상록구 (41271)
  '41271': {
    '10100': '10400', '10200': '10300', '10300': '10200', '10400': '10700', '10500': '10800',
    '10600': '10900', '10700': '10100',
  },
  // 안산시 단원구 (41273)
  '41273': {
    '10100': '10100', '10200': '10200', '10300': '10800', '10400': '10900', '10500': '10700',
    '10600': '10500',
  },
  // 고양시 덕양구 (41281)
  '41281': {
    '10100': '12800', '10200': '12300', '10300': '10300', '10400': '11100', '10500': '10400',
    '10600': '10100', '10700': '12200', '10800': '10600', '10900': '13200',
  },
  // 고양시 일산동구 (41285)
  '41285': {
    '10100': '10600', '10200': '10500', '10300': '10400', '10400': '10300', '10500': '10700',
    '10600': '10100', '10700': '10200', '10800': '10800',
  },
  // 고양시 일산서구 (41287)
  '41287': {
    '10100': '10200', '10200': '10400', '10300': '10100', '10400': '10300', '10500': '10500',
    '10600': '10600',
  },
  // 과천시 (41290)
  '41290': {
    '10100': '10700', '10200': '11000', '10300': '10900', '10400': '10300', '10500': '10200',
    '10600': '10500', '10700': '10600', '10800': '10400',
  },
  // 구리시 (41310)
  '41310': {
    '10100': '10400', '10200': '10300', '10300': '10100', '10400': '10500', '10500': '10700',
  },
  // 남양주시 (41360)
  '41360': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10400', '10500': '11200',
    '10600': '11100', '10700': '10700', '10800': '10800', '10900': '10900', '11000': '11000',
  },
  // 오산시 (41370)
  '41370': {
    '10100': '10100', '10200': '10300', '10300': '11300', '10400': '10500', '10500': '10200',
  },
  // 시흥시 (41390)
  '41390': {
    '10100': '13200', '10200': '10100', '10300': '10200', '10400': '10600', '10500': '10800',
    '10600': '12600', '10700': '13500', '10800': '11800', '10900': '12700',
  },
  // 군포시 (41410)
  '41410': {
    '10100': '10400', '10200': '10500', '10300': '10300', '10400': '10100', '10500': '10200',
    '10600': '10300',
  },
  // 의왕시 (41430)
  '41430': {
    '10100': '10700', '10200': '10500', '10300': '10600', '10400': '10900', '10500': '11000',
    '10600': '10800',
  },
  // 하남시 (41450)
  '41450': {
    '10100': '10600', '10200': '10800', '10300': '11000', '10400': '11100', '10500': '11400',
    '10600': '10900', '10700': '11300', '10800': '10100', '10900': '10300', '11000': '11000',
  },
  // 용인시 처인구 (41461)
  '41461': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10500', '10500': '10600',
    '10600': '10700', '10700': '10800', '10800': '10900',
  },
  // 용인시 기흥구 (41463)
  '41463': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10500', '10500': '10100',
    '10600': '11100', '10700': '11200', '10800': '11300', '10900': '11500', '11000': '11600',
    '11100': '11000',
  },
  // 용인시 수지구 (41465)
  '41465': {
    '10100': '10100', '10200': '10200', '10300': '10300', '10400': '10400', '10500': '10500',
    '10600': '10600', '10700': '10700',
  },
  // 파주시 (41480)
  '41480': {
    '10100': '10100', '10200': '10700', '10300': '10800', '10400': '11500', '10500': '10900',
    '10700': '10700', '10800': '11700',
  },
  // 이천시 (41500)
  '41500': {
    '10100': '10300', '10200': '10200', '10300': '10100', '10400': '10900', '10500': '11100',
  },
  // 김포시 (41570)
  '41570': {
    '10100': '10400', '10200': '10900', '10300': '10800', '10400': '10300', '10500': '10700',
    '10600': '10600', '10700': '10200', '10800': '10100', '10900': '10500', '11000': '11000',
  },
  // 화성시 (41590)
  '41590': {
    '10100': '10100', '10200': '12700', '10300': '12800', '10400': '13100', '10500': '13600',
    '10600': '12900', '10700': '13000', '10800': '11700', '10900': '11600', '11000': '12000',
    '11100': '11100', '11200': '13400', '11300': '13500', '11400': '12500',
  },
  // 광주시 (41610)
  '41610': {
    '10100': '10100', '10200': '10300', '10300': '10200', '10400': '11200', '10500': '11000',
    '10600': '11300',
  },
  // 양주시 (41630)
  '41630': {
    '10100': '11400', '10200': '10200', '10300': '10900', '10400': '11600', '10500': '10500',
    '10600': '10600',
  },
};

/**
 * Convert MOLIT dong code to Building Registry dong code
 */
function convertToRegistryDongCode(sigunguCd: string, molitDongCode: string): string {
  const districtMapping = MOLIT_TO_REGISTRY_DONG_CODE[sigunguCd];
  if (districtMapping && districtMapping[molitDongCode]) {
    const converted = districtMapping[molitDongCode];
    if (converted !== molitDongCode) {
      console.log(`[BuildingRegistry] Converting dong code: ${molitDongCode} → ${converted}`);
    }
    return converted;
  }
  // Return original if no mapping exists
  return molitDongCode;
}

// Mapping of building use codes to our BuildingType
// Note: API returns mainPurpsCdNm like "공동주택", "아파트", "연립주택" etc.
const BUILDING_TYPE_MAP: Record<string, BuildingType> = {
  // 아파트 (Apartments)
  '아파트': 'apartment',
  '주상복합': 'apartment', // Mixed-use residential
  '공동주택': 'apartment', // Generic apartment housing (need to check floor count for distinction)

  // 연립/다세대 (Multi-family)
  '연립주택': 'multifamily',
  '다세대주택': 'multifamily',
  '다가구주택': 'multifamily',
  '빌라': 'multifamily',

  // Other categories that should be treated as multifamily for our purposes
  '단독주택': 'multifamily', // Single-family but treat as multifamily for analysis

  // 오피스텔 (Officetel) - Not yet supported for analysis
  '오피스텔': 'officetel',
  '업무시설': 'officetel', // Business facilities (often includes officetel)
};

export class BuildingRegistryAPI {
  private apiKey: string;
  private baseUrl = 'https://apis.data.go.kr/1613000/BldRgstHubService';

  constructor(apiKey?: string) {
    this.apiKey = apiKey || process.env.BUILDING_REGISTRY_API_KEY || '';
  }

  /**
   * Get building information including building type
   * Uses 건축물대장 표제부 (title section) which contains building classification
   *
   * @param sigunguCd - 시군구코드 (district code, e.g., "11680" for 강남구)
   * @param bjdongCd - 법정동코드 (legal dong code, e.g., "10300" for 역삼동)
   * @param bun - 본번 (main lot number)
   * @param ji - 부번 (sub lot number, optional)
   */
  async getBuildingInfo(
    sigunguCd: string,
    bjdongCd: string,
    bun: string,
    ji?: string
  ): Promise<BuildingRegistryResponse> {
    if (!this.apiKey) {
      console.warn('[BuildingRegistry] No API key configured, returning unknown');
      return {
        success: false,
        error: 'API key not configured'
      };
    }

    try {
      // Convert MOLIT dong code to Building Registry dong code
      const registryDongCode = convertToRegistryDongCode(sigunguCd, bjdongCd);

      // Debug: log API request parameters
      const apiParams = {
        sigunguCd: sigunguCd,
        bjdongCd: registryDongCode,
        bun: bun.padStart(4, '0'),
        ji: (ji || '0').padStart(4, '0'),
      };
      console.log(`[BuildingRegistry] API Request params:`, apiParams);

      // Use getBrTitleInfo for 표제부 (title section) which has building type
      const response = await axios.get(
        `${this.baseUrl}/getBrTitleInfo`,
        {
          params: {
            serviceKey: this.apiKey,
            sigunguCd: sigunguCd,
            bjdongCd: registryDongCode,
            bun: bun.padStart(4, '0'), // API expects 4-digit format
            ji: (ji || '0').padStart(4, '0'), // API expects 4-digit format
            numOfRows: 10,
            pageNo: 1,
            _type: 'json'
          },
          timeout: 10000
        }
      );

      const result = response.data;

      // Debug: log raw response structure
      console.log(`[BuildingRegistry] Raw response for ${sigunguCd}-${registryDongCode}-${bun}-${ji}:`, {
        hasResponse: !!result.response,
        hasBody: !!result.response?.body,
        hasItems: !!result.response?.body?.items,
        itemsType: typeof result.response?.body?.items,
        itemsValue: result.response?.body?.items,
        totalCount: result.response?.body?.totalCount,
      });

      // Handle API response quirks: items can be empty string, null, or object/array
      const itemsWrapper = result.response?.body?.items;
      const items = itemsWrapper && typeof itemsWrapper === 'object' ? itemsWrapper.item : null;

      if (!items || (Array.isArray(items) && items.length === 0)) {
        console.log(`[BuildingRegistry] No building found for ${sigunguCd}-${bjdongCd}-${bun}-${ji}`);
        return {
          success: false,
          error: 'Building not found'
        };
      }

      // Normalize to array
      const itemArray = Array.isArray(items) ? items : [items];

      // For complexes, API may return multiple buildings (동)
      // We need to analyze all buildings to determine the correct type
      // Priority: 아파트 > 연립주택/다세대주택 > 공동주택 > others
      let maxFloorCount = 0;
      let totalFloorAreaSum = 0;
      let primaryBuildingType = '';
      let selectedItem = itemArray[0];

      // Track all building types found for better classification
      const foundTypes = new Set<string>();

      for (const item of itemArray) {
        const floors = item.grndFlrCnt ? parseInt(item.grndFlrCnt) : 0;
        const area = item.totArea ? parseFloat(item.totArea) : 0;
        const typeName = item.mainPurpsCdNm?.trim() || '';

        totalFloorAreaSum += area;
        if (typeName) foundTypes.add(typeName);

        // Track the building with highest floor count
        if (floors > maxFloorCount) {
          maxFloorCount = floors;
          selectedItem = item;
        }

        // Explicit building types take priority (highest to lowest)
        // 1. 아파트 - highest priority
        // 2. 연립주택/다세대주택 - explicit multifamily types
        // 3. Other types
        if (typeName === '아파트') {
          primaryBuildingType = '아파트';
        } else if (typeName === '연립주택' || typeName === '다세대주택' || typeName === '다가구주택') {
          // Only set if we haven't found 아파트
          if (primaryBuildingType !== '아파트') {
            primaryBuildingType = typeName;
          }
        } else if (!primaryBuildingType && typeName) {
          primaryBuildingType = typeName;
        }
      }

      // Log all found types for debugging
      console.log(`[BuildingRegistry] Found building types on lot: [${Array.from(foundTypes).join(', ')}]`);

      const mainPurpsCdNm = primaryBuildingType || selectedItem.mainPurpsCdNm?.trim() || '';
      const etcPurps = selectedItem.etcPurps?.trim() || ''; // 기타용도 - may contain specific type like "오피스텔(주거용)"
      // Use max floor count across all buildings for classification
      const groundFloors = maxFloorCount || (selectedItem.grndFlrCnt ? parseInt(selectedItem.grndFlrCnt) : 0);
      const buildingType = this.mapBuildingType(mainPurpsCdNm, groundFloors, totalFloorAreaSum, etcPurps);

      console.log(`[BuildingRegistry] Mapping: mainPurpsCdNm="${mainPurpsCdNm}", etcPurps="${etcPurps}", floors=${groundFloors}`);

      console.log(`[BuildingRegistry] Found ${itemArray.length} building(s): ${mainPurpsCdNm}, maxFloors=${maxFloorCount}, totalArea=${totalFloorAreaSum.toFixed(0)}㎡ → ${buildingType}`);

      return {
        success: true,
        data: {
          buildingType,
          buildingTypeName: mainPurpsCdNm,
          mainPurpsCd: selectedItem.mainPurpsCd || '',
          totalFloorArea: totalFloorAreaSum || undefined,
          groundFloorCount: maxFloorCount || undefined,
          undergroundFloorCount: selectedItem.ugrndFlrCnt ? parseInt(selectedItem.ugrndFlrCnt) : undefined,
          useAprDay: selectedItem.useAprDay || undefined
        }
      };
    } catch (error: any) {
      console.error('[BuildingRegistry] API Error:', error.message);
      return {
        success: false,
        error: error.message || 'Failed to fetch building info'
      };
    }
  }

  /**
   * Detect building type from address components
   * Convenience method that calls getBuildingInfo and returns just the type
   */
  async detectBuildingType(
    sigunguCd: string,
    bjdongCd: string,
    bun: string,
    ji?: string
  ): Promise<BuildingType> {
    const result = await this.getBuildingInfo(sigunguCd, bjdongCd, bun, ji);
    return result.data?.buildingType || 'unknown';
  }

  /**
   * Map Korean building type name to our BuildingType enum
   * Uses floor count and total floor area as indicators for ambiguous categories
   *
   * Korean building classification:
   * - 아파트: 5+ stories, typically high-rise
   * - 연립주택: 4 stories or less, total floor area > 660㎡
   * - 다세대주택: 4 stories or less, total floor area ≤ 660㎡
   *
   * IMPORTANT: mainPurpsCdNm (주용도) takes priority over etcPurps (기타용도)
   * because a lot can have multiple building types and we want to classify
   * based on the primary use, not secondary uses.
   */
  private mapBuildingType(koreanName: string, floorCount: number = 0, totalFloorArea: number = 0, etcPurps: string = ''): BuildingType {
    // Direct lookup for explicit types - mainPurpsCdNm takes priority
    // This ensures that if a lot has both 연립다세대 and 오피스텔,
    // and mainPurpsCdNm says 연립주택/다세대주택, we classify as multifamily
    if (koreanName === '아파트') return 'apartment';
    if (koreanName === '연립주택' || koreanName === '다세대주택' || koreanName === '다가구주택') {
      return 'multifamily';
    }

    // Check etcPurps (기타용도) only if mainPurpsCdNm doesn't give us a clear answer
    // etcPurps may contain specific types like "오피스텔(주거용)"
    if (etcPurps) {
      const lowerEtcPurps = etcPurps.toLowerCase();
      if (lowerEtcPurps.includes('오피스텔')) {
        return 'officetel';
      }
    }

    // For 공동주택 (generic apartment housing), use multiple heuristics
    // Korean law: 아파트 = 5+ stories, 연립/다세대 = 4 stories or less
    if (koreanName === '공동주택') {
      // If we have floor count data, use it
      if (floorCount >= 5) {
        return 'apartment';
      }
      // If floor count is between 1-4, it's multifamily
      if (floorCount > 0 && floorCount < 5) {
        return 'multifamily';
      }
      // Floor count is 0 (missing data) - use total floor area as heuristic
      // Large floor area (>5000㎡) indicates apartment complex
      // (Typical 연립/다세대 buildings are much smaller)
      if (totalFloorArea > 5000) {
        return 'apartment';
      }
      // If no reliable data, default to apartment for 공동주택
      // (Modern developments registered as 공동주택 are more commonly apartments)
      return 'apartment';
    }

    // Check mapping table
    if (BUILDING_TYPE_MAP[koreanName]) {
      return BUILDING_TYPE_MAP[koreanName];
    }

    // Partial matching for variants
    const lowerName = koreanName.toLowerCase();

    if (lowerName.includes('아파트') || lowerName.includes('apartment')) {
      return 'apartment';
    }

    if (
      lowerName.includes('연립') ||
      lowerName.includes('다세대') ||
      lowerName.includes('다가구') ||
      lowerName.includes('빌라')
    ) {
      return 'multifamily';
    }

    // 오피스텔 detection
    if (lowerName.includes('오피스텔') || lowerName.includes('officetel')) {
      return 'officetel';
    }

    // For unknown types, use floor count as heuristic
    // High-rise (5+) more likely to be apartment-style
    if (floorCount >= 5) {
      return 'apartment';
    }

    // If total floor area is very large, likely apartment
    if (totalFloorArea > 5000) {
      return 'apartment';
    }

    // Default to unknown for other building types
    return 'unknown';
  }
}

// Export singleton instance for convenience
export const buildingRegistryAPI = new BuildingRegistryAPI();
